//
//  Song.swift
//  Filter List Of Songs
//
//  Created by Philipp Schadt on 19.01.24.
//

import SwiftUI

struct Song: Identifiable {
    let id: UUID
    let artist: String
    let title: String
    let year: Int
    
    init(artist: String, title: String, yearOfPublish: Int) {
        self.id = UUID()
        self.artist = artist
        self.title = title
        self.year = yearOfPublish
    }
}

var songs = [
    Song(artist: "Eminem", title: "Without Me", yearOfPublish: 2002),
    Song(artist: "Eminem", title: "Lose Yourself", yearOfPublish: 2002),
    Song(artist: "Eminem", title: "Stan", yearOfPublish: 2000),
    Song(artist: "Eminem", title: "The Real Slim Shady", yearOfPublish: 2000),
    Song(artist: "Eminem", title: "Mockingbird", yearOfPublish: 2004),
    Song(artist: "Eminem", title: "Love the Way You Lie", yearOfPublish: 2010),
    Song(artist: "Eminem", title: "Not Afraid", yearOfPublish: 2010),
    Song(artist: "Eminem", title: "Rap God", yearOfPublish: 2013),
    Song(artist: "Eminem", title: "Venom", yearOfPublish: 2018),
    Song(artist: "Eminem", title: "Godzilla", yearOfPublish: 2020),
    Song(artist: "Taylor Swift", title: "Shake It Off", yearOfPublish: 2014),
    Song(artist: "Ed Sheeran", title: "Shape of You", yearOfPublish: 2017),
    Song(artist: "Beyoncé", title: "Single Ladies (Put a Ring on It)", yearOfPublish: 2008),
    Song(artist: "Drake", title: "Hotline Bling", yearOfPublish: 2015),
    Song(artist: "Adele", title: "Rolling in the Deep", yearOfPublish: 2010),
    Song(artist: "Kanye West", title: "Stronger", yearOfPublish: 2007),
    Song(artist: "Rihanna", title: "Umbrella", yearOfPublish: 2007),
    Song(artist: "Justin Bieber", title: "Sorry", yearOfPublish: 2015),
    Song(artist: "Ariana Grande", title: "Thank U, Next", yearOfPublish: 2018),
    Song(artist: "Post Malone", title: "Circles", yearOfPublish: 2019),
    Song(artist: "The Weeknd", title: "Blinding Lights", yearOfPublish: 2019),
    Song(artist: "Billie Eilish", title: "Bad Guy", yearOfPublish: 2019),
    Song(artist: "Katy Perry", title: "Firework", yearOfPublish: 2010),
    Song(artist: "Imagine Dragons", title: "Radioactive", yearOfPublish: 2012),
    Song(artist: "Lady Gaga", title: "Poker Face", yearOfPublish: 2008),
    Song(artist: "Bruno Mars", title: "Uptown Funk", yearOfPublish: 2014),
    Song(artist: "Maroon 5", title: "Sugar", yearOfPublish: 2014),
    Song(artist: "Sia", title: "Chandelier", yearOfPublish: 2014),
    Song(artist: "Sam Smith", title: "Stay With Me", yearOfPublish: 2014),
    Song(artist: "Lorde", title: "Royals", yearOfPublish: 2013),
    Song(artist: "Shawn Mendes", title: "Stitches", yearOfPublish: 2014),
    Song(artist: "Camila Cabello", title: "Havana", yearOfPublish: 2017),
    Song(artist: "Dua Lipa", title: "New Rules", yearOfPublish: 2017),
    Song(artist: "Panic! At The Disco", title: "High Hopes", yearOfPublish: 2018),
    Song(artist: "Travis Scott", title: "SICKO MODE", yearOfPublish: 2018),
    Song(artist: "Cardi B", title: "Bodak Yellow", yearOfPublish: 2017),
    Song(artist: "Twenty One Pilots", title: "Stressed Out", yearOfPublish: 2015),
    Song(artist: "Macklemore & Ryan Lewis", title: "Thrift Shop", yearOfPublish: 2012),
    Song(artist: "Halsey", title: "Without Me", yearOfPublish: 2018),
    Song(artist: "Ariana Grande", title: "7 Rings", yearOfPublish: 2019),
    Song(artist: "Charlie Puth", title: "Attention", yearOfPublish: 2017),
    Song(artist: "Eminem", title: "The Monster", yearOfPublish: 2013),
    Song(artist: "Zedd", title: "Clarity", yearOfPublish: 2012),
    Song(artist: "Adele", title: "Someone Like You", yearOfPublish: 2011),
    Song(artist: "John Legend", title: "All of Me", yearOfPublish: 2013),
    Song(artist: "Khalid", title: "Young Dumb & Broke", yearOfPublish: 2017),
    Song(artist: "Clean Bandit", title: "Rather Be", yearOfPublish: 2014),
    Song(artist: "Calvin Harris", title: "Feel So Close", yearOfPublish: 2011),
    Song(artist: "Usher", title: "DJ Got Us Fallin' In Love", yearOfPublish: 2010),
    Song(artist: "Miley Cyrus", title: "Wrecking Ball", yearOfPublish: 2013),
    Song(artist: "Justin Timberlake", title: "Can't Stop the Feeling!", yearOfPublish: 2016),
    Song(artist: "The Chainsmokers", title: "Closer", yearOfPublish: 2016),
    Song(artist: "Marshmello", title: "Happier", yearOfPublish: 2018),
    Song(artist: "Selena Gomez", title: "Bad Liar", yearOfPublish: 2017),
    Song(artist: "Demi Lovato", title: "Sorry Not Sorry", yearOfPublish: 2017),
    Song(artist: "Shakira", title: "Waka Waka (This Time for Africa)", yearOfPublish: 2010),
    Song(artist: "Avicii", title: "Wake Me Up", yearOfPublish: 2013),
    Song(artist: "OneRepublic", title: "Counting Stars", yearOfPublish: 2013),
    Song(artist: "Nicki Minaj", title: "Super Bass", yearOfPublish: 2011),
    Song(artist: "Rihanna", title: "Diamonds", yearOfPublish: 2012),
    Song(artist: "P!nk", title: "Just Give Me a Reason", yearOfPublish: 2012),
    Song(artist: "Daft Punk", title: "Get Lucky", yearOfPublish: 2013),
    Song(artist: "Imagine Dragons", title: "Demons", yearOfPublish: 2012),
    Song(artist: "Coldplay", title: "Viva La Vida", yearOfPublish: 2008),
    Song(artist: "Eminem", title: "Beautiful", yearOfPublish: 2009),
    Song(artist: "R.E.M.", title: "Losing My Religion", yearOfPublish: 1991),
    Song(artist: "Linkin Park", title: "In the End", yearOfPublish: 2001),
    Song(artist: "Nirvana", title: "Smells Like Teen Spirit", yearOfPublish: 1991),
    Song(artist: "Queen", title: "Bohemian Rhapsody", yearOfPublish: 1975),
    Song(artist: "Adele", title: "Hello", yearOfPublish: 2015),
    Song(artist: "Justin Bieber", title: "Love Yourself", yearOfPublish: 2015),
    Song(artist: "Shawn Mendes", title: "Señorita", yearOfPublish: 2019),
    Song(artist: "Post Malone", title: "Rockstar", yearOfPublish: 2017),
    Song(artist: "Camila Cabello", title: "Havana", yearOfPublish: 2017),
    Song(artist: "Ariana Grande", title: "Break Free", yearOfPublish: 2014),
    Song(artist: "Imagine Dragons", title: "Believer", yearOfPublish: 2017),
    Song(artist: "Billie Eilish", title: "When The Party's Over", yearOfPublish: 2018),
    Song(artist: "Ed Sheeran", title: "Castle on the Hill", yearOfPublish: 2017),
    Song(artist: "The Weeknd", title: "Can't Feel My Face", yearOfPublish: 2015),
    Song(artist: "Khalid", title: "Talk", yearOfPublish: 2019),
    Song(artist: "Dua Lipa", title: "Don't Start Now", yearOfPublish: 2019),
    Song(artist: "Drake", title: "God's Plan", yearOfPublish: 2018),
    Song(artist: "Taylor Swift", title: "Blank Space", yearOfPublish: 2014),
    Song(artist: "Sam Smith", title: "I'm Not The Only One", yearOfPublish: 2014),
    Song(artist: "Katy Perry", title: "Roar", yearOfPublish: 2013),
    Song(artist: "The Chainsmokers", title: "Don't Let Me Down", yearOfPublish: 2016),
    Song(artist: "Coldplay", title: "Fix You", yearOfPublish: 2005),
    Song(artist: "Bruno Mars", title: "Just the Way You Are", yearOfPublish: 2010),
    Song(artist: "Ariana Grande", title: "No Tears Left To Cry", yearOfPublish: 2018),
    Song(artist: "Sia", title: "Cheap Thrills", yearOfPublish: 2016),
    Song(artist: "Hozier", title: "Take Me to Church", yearOfPublish: 2013),
    Song(artist: "Panic! At The Disco", title: "Death of a Bachelor", yearOfPublish: 2015),
    Song(artist: "Twenty One Pilots", title: "Heathens", yearOfPublish: 2016),
    Song(artist: "Miley Cyrus", title: "Party in the U.S.A.", yearOfPublish: 2009),
    Song(artist: "Charlie Puth", title: "We Don't Talk Anymore", yearOfPublish: 2016),
    Song(artist: "Cardi B", title: "I Like It", yearOfPublish: 2018),
    Song(artist: "Maroon 5", title: "Maps", yearOfPublish: 2014),
    Song(artist: "Eminem", title: "Berzerk", yearOfPublish: 2013),
    Song(artist: "OneRepublic", title: "Apologize", yearOfPublish: 2006),
    Song(artist: "Rihanna", title: "We Found Love", yearOfPublish: 2011),
    Song(artist: "Justin Timberlake", title: "Mirrors", yearOfPublish: 2013),
    Song(artist: "Zedd", title: "The Middle", yearOfPublish: 2018),
    Song(artist: "Calvin Harris", title: "Summer", yearOfPublish: 2014),
    Song(artist: "Alicia Keys", title: "Empire State of Mind", yearOfPublish: 2009),
    Song(artist: "Luis Fonsi", title: "Despacito", yearOfPublish: 2017),
    Song(artist: "Lady Gaga", title: "Bad Romance", yearOfPublish: 2009),
    Song(artist: "Kanye West", title: "Heartless", yearOfPublish: 2008),
    Song(artist: "Foster The People", title: "Pumped Up Kicks", yearOfPublish: 2010),
    Song(artist: "Selena Gomez", title: "Wolves", yearOfPublish: 2017),
    Song(artist: "Demi Lovato", title: "Skyscraper", yearOfPublish: 2011),
    Song(artist: "Shakira", title: "Hips Don't Lie", yearOfPublish: 2005),
    Song(artist: "Adele", title: "Rolling in the Deep", yearOfPublish: 2010),
    Song(artist: "Ariana Grande", title: "Into You", yearOfPublish: 2016),
    Song(artist: "Jason Derulo", title: "Want to Want Me", yearOfPublish: 2015),
    Song(artist: "Eminem", title: "Space Bound", yearOfPublish: 2010),
    Song(artist: "Taylor Swift", title: "Style", yearOfPublish: 2014),
    Song(artist: "Nicki Minaj", title: "Anaconda", yearOfPublish: 2014),
    Song(artist: "Justin Bieber", title: "Sorry", yearOfPublish: 2015),
    Song(artist: "Sia", title: "Elastic Heart", yearOfPublish: 2013),
    Song(artist: "Avicii", title: "Levels", yearOfPublish: 2011),
    Song(artist: "Ellie Goulding", title: "Love Me Like You Do", yearOfPublish: 2015),
    Song(artist: "Imagine Dragons", title: "Thunder", yearOfPublish: 2017),
    Song(artist: "The Weeknd", title: "Starboy", yearOfPublish: 2016),
    Song(artist: "Billie Eilish", title: "Ocean Eyes", yearOfPublish: 2016),
    Song(artist: "Ed Sheeran", title: "Photograph", yearOfPublish: 2015),
    Song(artist: "Sam Smith", title: "Stay With Me", yearOfPublish: 2014),
    Song(artist: "Khalid", title: "Location", yearOfPublish: 2016),
    Song(artist: "Dua Lipa", title: "IDGAF", yearOfPublish: 2017),
    Song(artist: "Drake", title: "In My Feelings", yearOfPublish: 2018),
    Song(artist: "Taylor Swift", title: "Shake It Off", yearOfPublish: 2014),
    Song(artist: "Charlie Puth", title: "Attention", yearOfPublish: 2017),
    Song(artist: "Zayn", title: "Pillowtalk", yearOfPublish: 2016),
    Song(artist: "Marshmello", title: "Alone", yearOfPublish: 2016),
    Song(artist: "Halsey", title: "Bad at Love", yearOfPublish: 2017),
    Song(artist: "P!nk", title: "What About Us", yearOfPublish: 2017),
    Song(artist: "Shawn Mendes", title: "If I Can't Have You", yearOfPublish: 2019),
    Song(artist: "Camila Cabello", title: "Never Be The Same", yearOfPublish: 2017),
    Song(artist: "Ariana Grande", title: "Dangerous Woman", yearOfPublish: 2016),
    Song(artist: "The Chainsmokers", title: "Roses", yearOfPublish: 2015),
    Song(artist: "Cardi B", title: "Bartier Cardi", yearOfPublish: 2017),
    Song(artist: "Maroon 5", title: "She Will Be Loved", yearOfPublish: 2004),
    Song(artist: "Eminem", title: "When I'm Gone", yearOfPublish: 2005),
    Song(artist: "Imagine Dragons", title: "Whatever It Takes", yearOfPublish: 2017),
    Song(artist: "Billie Eilish", title: "Bury A Friend", yearOfPublish: 2019),
    Song(artist: "Ed Sheeran", title: "Thinking Out Loud", yearOfPublish: 2014),
    Song(artist: "The Weeknd", title: "The Hills", yearOfPublish: 2015),
    Song(artist: "Khalid", title: "Better", yearOfPublish: 2018),
    Song(artist: "Dua Lipa", title: "Be The One", yearOfPublish: 2015),
    Song(artist: "Drake", title: "Hotline Bling", yearOfPublish: 2015),
    Song(artist: "Taylor Swift", title: "Love Story", yearOfPublish: 2008),
    Song(artist: "Sam Smith", title: "Too Good at Goodbyes", yearOfPublish: 2017),
    Song(artist: "Katy Perry", title: "California Gurls", yearOfPublish: 2010),
    Song(artist: "The Chainsmokers", title: "Something Just Like This", yearOfPublish: 2017),
    Song(artist: "Coldplay", title: "Viva La Vida", yearOfPublish: 2008),
    Song(artist: "Bruno Mars", title: "Locked Out of Heaven", yearOfPublish: 2012),
    Song(artist: "Ariana Grande", title: "One Last Time", yearOfPublish: 2014),
    Song(artist: "Sia", title: "The Greatest", yearOfPublish: 2016),
    Song(artist: "Hozier", title: "Arsonist's Lullabye", yearOfPublish: 2016),
    Song(artist: "Panic! At The Disco", title: "I Write Sins Not Tragedies", yearOfPublish: 2005),
    Song(artist: "Cro", title: "Easy", yearOfPublish: 2011),
    Song(artist: "Helene Fischer", title: "Atemlos durch die Nacht", yearOfPublish: 2013),
    Song(artist: "Mark Forster", title: "Chöre", yearOfPublish: 2016),
    Song(artist: "Peter Fox", title: "Haus am See", yearOfPublish: 2008),
    Song(artist: "Die Fantastischen Vier", title: "Die Da!?! (Ich schwör)", yearOfPublish: 1992),
    Song(artist: "Namika", title: "Lieblingsmensch", yearOfPublish: 2015),
    Song(artist: "Herbert Grönemeyer", title: "Mensch", yearOfPublish: 2002),
    Song(artist: "Xavier Naidoo", title: "Dieser Weg", yearOfPublish: 2005),
    Song(artist: "Silbermond", title: "Das Beste", yearOfPublish: 2006),
    Song(artist: "Max Giesinger", title: "80 Millionen", yearOfPublish: 2016),
    Song(artist: "Nena", title: "99 Luftballons", yearOfPublish: 1983),
    Song(artist: "Sido", title: "Bilder im Kopf", yearOfPublish: 2012),
    Song(artist: "Tim Bendzko", title: "Nur noch kurz die Welt retten", yearOfPublish: 2011),
    Song(artist: "Revolverheld", title: "Ich lass für dich das Licht an", yearOfPublish: 2010),
    Song(artist: "Udo Lindenberg", title: "Hinterm Horizont geht's weiter", yearOfPublish: 1986),
    Song(artist: "Helene Fischer", title: "Herzbeben", yearOfPublish: 2016),
    Song(artist: "Xavier Naidoo", title: "Wo willst du hin?", yearOfPublish: 1998),
    Song(artist: "Cro", title: "Traum", yearOfPublish: 2014),
    Song(artist: "Die Fantastischen Vier", title: "Ernten was wir säen", yearOfPublish: 2004),
    Song(artist: "Nena", title: "Irgendwie, irgendwo, irgendwann", yearOfPublish: 1984),
    Song(artist: "Sido", title: "Mein Block", yearOfPublish: 2004),
    Song(artist: "Revolverheld", title: "Spinner", yearOfPublish: 2010),
    Song(artist: "Die Toten Hosen", title: "Liebeslied", yearOfPublish: 1988),
    Song(artist: "Die Prinzen", title: "Deutschland", yearOfPublish: 1993),
    Song(artist: "Juli", title: "Perfekte Welle", yearOfPublish: 2004),
    Song(artist: "Die Fantastischen Vier", title: "Troy", yearOfPublish: 1999),
    Song(artist: "Die Toten Hosen", title: "Liebeslied", yearOfPublish: 1988),
    Song(artist: "Die Prinzen", title: "Deutschland", yearOfPublish: 1993),
    Song(artist: "Wir sind Helden", title: "Nur ein Wort", yearOfPublish: 2003),
    Song(artist: "Juli", title: "Perfekte Welle", yearOfPublish: 2004),
    Song(artist: "Die Fantastischen Vier", title: "Troy", yearOfPublish: 1999),
    Song(artist: "Helene Fischer", title: "Phänomen", yearOfPublish: 2008),
    Song(artist: "Enrique Iglesias", title: "Bailando", yearOfPublish: 2014),
    Song(artist: "Shakira", title: "La Tortura", yearOfPublish: 2005),
    Song(artist: "J Balvin", title: "Ginza", yearOfPublish: 2015),
    Song(artist: "Luis Fonsi", title: "Despacito (Remix)", yearOfPublish: 2017),
    Song(artist: "Ricky Martin", title: "Livin' la Vida Loca", yearOfPublish: 1999),
    Song(artist: "Maluma", title: "Felices los 4", yearOfPublish: 2017),
    Song(artist: "Juanes", title: "A Dios le Pido", yearOfPublish: 2002),
    Song(artist: "Daddy Yankee", title: "Gasolina", yearOfPublish: 2004),
    Song(artist: "Marc Anthony", title: "Vivir Mi Vida", yearOfPublish: 2013),
]
